name: Update Contribution Graph

on:
  schedule:
    - cron: "25 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v6

      - name: Generate contribution graph
        env:
          PROFILE_TOKEN: ${{ secrets.PROFILE_TOKEN }}
          GITHUB_USERNAME: MaorMalka
        run: python scripts/generate_contribution_graph.py

      - name: Commit updated graph
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/contribution-graph.svg

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update contribution graph"
          git push
